/**********
Copyright 1990 Regents of the University of California.  All rights reserved.
**********/

#include "ngspice.h"
#include "compdefs.h"
#include "cktdefs.h"
#include "iferrmsg.h"
#include "noisedef.h"

/*
 * COMPnoise (mode, operation, firstModel, ckt, data, OnDens)
 *    This routine names and evaluates all of the noise sources
 *    associated with resistors.  It starts with the model *firstModel
 *    and traverses all of its instances.  It then proceeds to any other
 *    models on the linked list.  The total output noise density
 *    generated by all the resistors is summed in the variable "OnDens".
 *
 * Paolo Nenzi 2003: 
 *    Added flicker noise (Kf-Af) calculation to simulate
 *    carbon resistors.
 *
 *    Added "noisy" switch to simulate noiseless resistors.
 */

int
COMPnoise (int mode, int operation, GENmodel *genmodel, CKTcircuit *ckt, 
          Ndata *data, double *OnDens)
{
  return(OK);
}
            

